# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024m -XX:+UseParallelGC

# When configured, Gradle will run in incubating parallel mode.
org.gradle.parallel=true
org.gradle.caching=true

# When enabled, the Configuration Cache allows Gradle to skip the configuration
org.gradle.configuration-cache=false

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
