name: Android Build

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/**'

permissions:
  contents: read

jobs:
  build:
    name: Build Check
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: set up jdk
        uses: actions/setup-java@v6
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: setup gradle
        uses: gradle/actions/setup-gradle@v3

      - name: grant execute permission for gradlew
        run: chmod +x gradlew

      - name: run Android lint
        run: bash gradlew lintDebug

      - name: compile code
        run: bash gradlew compileDebugSources
